### ISSUE TITLE
Github Action for running Solana tests

### ISSUE THREAD

**Issue by briangershon** [briangershon/solana-clicker-game#21]
I started with this snippet from <https://dev.to/lazar955/create-a-github-action-to-run-solana-anchor-tests-5f5l> and it worked well, except it needs a wallet keypair when running the tests.

```
name: Solana Clicker UI and program tests
on:
    push:
        paths-ignore:
            - '**.md'

env:
  SOLANA_VERSION: v1.10.8
  ANCHOR_VERSION: 0.24.2

jobs:
    # From https://dev.to/lazar955/create-a-github-action-to-run-solana-anchor-tests-5f5l
    run-solana-tests:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v3
              with:
                node-version: 16.x
                cache: "npm"
            - run: yarn
              working-directory: program
            - run: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
              shell: bash
              working-directory: program
            - run: echo "/home/runner/.cargo/bin" >> $GITHUB_PATH
              shell: bash
              working-directory: program
            - run: curl -sSfL https://release.solana.com/$SOLANA_VERSION/install | sh
              shell: bash
              working-directory: program
            - run: echo "/home/runner/.local/share/solana/install/active_release/bin" >> $GITHUB_PATH
              shell: bash
              working-directory: program
            - run: npm i -g @project-serum/anchor-cli@$ANCHOR_VERSION ts-mocha typescript
              working-directory: program
            - run: anchor test
              working-directory: program

```
